// action-types.js
export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_FAILURE = "FETCH_POKEMONS_FAILURE";
export const SET_SELECTED_POKEMON = "SET_SELECTED_POKEMON";
export const CREATE_POKEMON_SUCCESS = 'CREATE_POKEMON_SUCCESS';
export const CREATE_POKEMON_ERROR = 'CREATE_POKEMON_ERROR';
export const FETCH_TYPES_SUCCESS = 'FETCH_TYPES_SUCCESS';
export const FETCH_TYPES_FAILURE = 'FETCH_TYPES_FAILURE';
export const DELETE_POKEMON_SUCCESS='DELETE_POKEMON_SUCCESS';
export const DELETE_POKEMON_FAILURE='DELETE_POKEMON_SUCCESS';
export const FILTER_BY_ORIGIN = 'FILTER_BY_ORIGIN';
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
export const RESET_FILTERED_POKEMONS = "RESET_FILTERED_POKEMONS";
export const SORT_POKEMONS = "SORT_POKEMONS";
export const SEARCH_POKEMON = "SEARCH_POKEMON";
