// action-types.js
export const FETCH_POKEMONS_SUCCESS = "FETCH_POKEMONS_SUCCESS";
export const FETCH_POKEMONS_FAILURE = "FETCH_POKEMONS_FAILURE";
export const SET_SELECTED_POKEMON = "SET_SELECTED_POKEMON";

